MODUL6 SHERLY/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/AddNewPost','AddNewPostController@index')->name('AddNewPost');
Route::get('/Profile','EditProfileController@index')->name('Profile');
Route::get('/EditProfile','EditProfileController@edit')->name('EditProfile');
Route::get('likeposts{id}','HomeController@like')->name('Like');
Route::get('DetailsPost/{id}','HomeController@specific')->name('DetailsPost');
Route::post('/home','HomeController@store')->name('home');
Route::resource('AddNewPost','AddNewPostController');

MODUL6 SHERLY/resources/views/AddNewPost.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
             <div class="col-8 offset-2">
 
               <div class="row">
                    <h1 style="color:magenta">Add New Post</h1>
                   </div>
                   <label for="caption" class="col-md-4 col-form-label">Post Caption</label>
                   <form action="{{route('AddNewPost.store')}}" method="post" enctype="multipart/form-data">
                   {{csrf_field()}}
    
       <input type="hidden" value="{{Auth::id()}}" name="id">
       <input type="text" name="caption"> <br>
       <label for="caption" class="col-md-4 col-form-label">Post Image</label> <br>
       <input type="file" name="foto"> <br> <br>
       <input type="submit" value="Add New Post" style="color:blue"> <br>
</form>

@endsection

MODUL6 SHERLY/resources/views/DetailsPost.blade.php
@extends('layouts.app')
@section('content')

<div class="card mb-3" style="max-width: 100%;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="../{{$posts->image}}" class="card-img" alt="post_image">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{$posts->users['email']}}</h5>     
        <h5 class="card-title" >{{$posts->caption}}</h5>
        @foreach($posts->comment as $cm)
        {{$cm['comment']}}
        @endforeach
        <hr>
      </div>
    </div>
  </div>
</div>
@endsection

MODUL6 SHERLY/resources/views/EditProfile.blade.php
@extends('layouts.app')
@section('content')

<center><a href="{{url('/AddNewPost')}}" style="color:magenta"><h1>Click here ->New Post</h1></a></center>
<form action="/profile/5" enctype="multipart/form-data" method="post">
        <input type="hidden" name="_token" value="b24KQlInfwDH7SO9Ehmnzx2squbyIcQQBJkmDGs4">        
        <input type="hidden" name="_method" value="PATCH">
        <div class="row">
            <div class="col-8 offset-2">

                <div class="row">
                    <h1>Edit Profile</h1>
                </div>
                <div class="form-group row">
                    <label for="title" class="col-md-4 col-form-label">Title</label>

                    <input id="title"
                           type="text"
                           class="form-control"
                           name="title"
                           value=""
                           autocomplete="title"
                           autofocus>

                                    </div>

                <div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label">Description</label>

                    <input id="description"
                           type="text"
                           class="form-control"
                           name="description"
                           value=""
                           autocomplete="description" autofocus>

                                    </div>

                <div class="form-group row">
                    <label for="url" class="col-md-4 col-form-label">URL</label>

                    <input id="url"
                           type="text"
                           class="form-control"
                           name="url"
                           value=""
                           autocomplete="url" autofocus>

                                    </div>

                <div class="row">
                    <label for="image" class="col-md-4 col-form-label">Profile Image</label>

                    <input type="file" class="form-control-file" id="image" name="image">

                                    </div>

                <div class="row pt-4">
                    <button class="btn btn-primary">Save Profile</button>
                </div>

            </div>
        </div>
    </form>
@endsection

MODUL6 SHERLY/resources/views/Profile.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
    <div class="row">
        <div class="col-3 p-5">
            <img src="{{Auth::user()->avatar}}" alt ="gambar" class="rounded-circle w-100">
        </div>
        <div class="col-9 pt-5">
            <div class="d-flex justify-content-between align-items-baseline">
                <div class="d-flex align-items-center pb-3">
                    <div class="h4">{{Auth::user()->name}}</div>
                </div>
                  <a href="/AddNewPost">Add New Post</a>  
            </div>

                <a href="/EditProfile">Edit Profile</a>
            
            <div class="d-flex">
                <div class="pr-5"><strong> ...</strong> posts</div>
            </div>
            <div class="pt-4 font-weight-bold"></div>
            <div></div>
            <div><a href=""></a></div>
        </div>
    </div>

    <div class="row pt-5">
            </div>
</div>
@endsection

MODUL6 SHERLY/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-5">
            @foreach($post as $pos)
            <div class="card">
                <div class="card-header">
                    <div class="container ">
                        <div class="row">
                            <div class="col-2">
                                <img src="{{$pos->users['avatar']}}" class="rounded-circle" alt="kosonggg" width="100%"
                                    height="35">
                            </div>
                           
                                <span class="text-dark"><b>{{$pos->users['name']}}</b></span> </a>
                        </div>
                    </div>

                </div>
                <a href="{{route('DetailsPost',$pos->id)}}">
                     <img src="{{ $pos->image }}" style="width:100%; height:350px;" alt="kosong"></a>
                <div class="card-header">
                    <div class="container">
                        <p>
                    
                            <a href="{{ route('Like',['id'=>$pos->id]) }}" class="">
                            <button class="btn" name="direct" value="home" type="submit"><i class="fa fa-heart-o"></i></button>

                                <a href="/Detailpost"><i class="fa fa-comment-o"></i></a>
                                <p><b>{{$pos->likes}}</b>likes</p>
                           
                                    <span class="text-dark"> <b>{{$pos->users['email']}}</b></a>
                                <p>{{ $pos->caption }}</p>
                                   

                                <form method="" enctype="multipart/form-data">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Recipient's Name"
                                            name="komen">
                                        <div class="input-group-append">
                                            <button class="btn btn-success" type="submit"
                                                style="background-color:grey;">Post</button>
                                        </div>
                                    </div>

                    </div>
                </div>
            </div>
            <br>
            @endforeach
        </div>
    </div>
    @endsection